# ---- Stage 1: build de la SPA ----
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci || npm install
COPY . .
ARG VITE_PUBLIC_BFF_URL=https://821dbjhp16.execute-api.us-east-1.amazonaws.com/prod
ENV VITE_PUBLIC_BFF_URL=$VITE_PUBLIC_BFF_URL
RUN npm run build

# ---- Stage 2: nginx sirviendo el build ----
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]